-- entity_vehicle_entries.sql
-- ============================================================
-- 車両管理（cars）
--
-- 重要（管理番号採番）:
-- - MySQL/MariaDB は AFTER INSERT トリガ内で同一テーブルを UPDATE すると #1442 になるため、
--   トリガ採番は採用しない。
-- - management_number は「INSERT後にアプリ側で UPDATE」して採番する（例: CAR-000000123）。
--
-- 例（アプリ側採番）:
--   UPDATE cars
--   SET management_number = CONCAT('CAR-', LPAD(id, 9, '0'))
--   WHERE id = :id AND (management_number IS NULL OR management_number = '');

DROP TABLE IF EXISTS cars;

CREATE TABLE `cars` (
  `id` bigint(20) UNSIGNED NOT NULL COMMENT 'PK',
  `management_number` varchar(20) DEFAULT NULL COMMENT '管理番号（登録後に自動採番）',
  `vehicle_number` varchar(32) DEFAULT NULL COMMENT '車両番号',
  `chassis_number` varchar(64) NOT NULL COMMENT '車台番号（必須）',
  `registration_year` smallint(5) UNSIGNED DEFAULT 0 COMMENT '登録年（0未選択）',
  `registration_month` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '登録月（0未選択/1-12）',
  `registration_day` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '登録日（0未選択/1-31）',
  `first_registration_year` smallint(5) UNSIGNED DEFAULT 0 COMMENT '初年度登録年（0未選択）',
  `first_registration_month` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '初年度登録月（0未選択/1-12）',
  `maker` varchar(50) DEFAULT NULL COMMENT 'メーカー（例: toyota, lexus）',
  `car_model` varchar(50) DEFAULT NULL COMMENT '車種（例: toyota001 等のコード）',
  `model_designation_number` varchar(32) DEFAULT NULL COMMENT '型式指定番号',
  `classification_division_number` varchar(32) DEFAULT NULL COMMENT '類別区分番号',
  `type_of_car` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '自動車の種別（0未選択/1軽/2小型/3普通/4大型特殊）',
  `car_purpose` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '用途（0未選択/1乗用/2貨物/3乗合/4特種）',
  `how_to_use` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '自家用・事業用（0未選択/1自家/2事業）',

  `status_code` tinyint(3) UNSIGNED NOT NULL DEFAULT 1 COMMENT '車両状態(1=在庫,2=リース中,3=お客様所有(販売済),4=代車,5=廃車)',

  `body_shape` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '車体の形状（0未選択/1箱型/2ステーションワゴン/3幌型）',
  `vehicle_weight` int(10) UNSIGNED DEFAULT NULL COMMENT '車両重量（kg想定）',
  `displacement` int(10) UNSIGNED DEFAULT NULL COMMENT '排気量（cc想定）',
  `new_used` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '新車/中古車（0未選択/1新車/2中古車）',
  `purchase_year` smallint(5) UNSIGNED DEFAULT 0 COMMENT '購入年（0未選択）',
  `purchase_month` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '購入月（0未選択/1-12）',
  `purchase_day` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '購入日（0未選択/1-31）',
  `purchase_price` bigint(20) UNSIGNED DEFAULT NULL COMMENT '車両購入価格（円）',
  `consumption_tax` bigint(20) UNSIGNED DEFAULT NULL COMMENT '消費税（円）',
  `recycling_cost` bigint(20) UNSIGNED DEFAULT NULL COMMENT 'リサイクル費用（円）',
  `purchase_costs` bigint(20) UNSIGNED DEFAULT NULL COMMENT '購入時諸費用（円）',
  `car_tax` bigint(20) UNSIGNED DEFAULT NULL COMMENT '自動車税（年額・入力値）（円）',
  `car_insurance_premium` bigint(20) UNSIGNED DEFAULT NULL COMMENT '自動車保険料（年額）（円）',
  `total_expenses` bigint(20) UNSIGNED DEFAULT NULL COMMENT '経費総額（円）',
  `model_year` smallint(5) UNSIGNED DEFAULT 0 COMMENT '年式（0未選択/1980〜）',
  `mileage_amount` int(10) UNSIGNED DEFAULT NULL COMMENT '走行距離（km想定）',
  `base_price` bigint(20) UNSIGNED DEFAULT NULL COMMENT '販売本体価格（円）',
  `total_to_pay` bigint(20) UNSIGNED DEFAULT NULL COMMENT '支払総額（円）',
  `one_owner` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ワンオーナー（0未選択/1該当/2非該当）',
  `camper` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'キャンピングカー（0未選択/1該当/2非該当）',
  `repair_history` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '修復歴（0未選択/1あり/2なし）',
  `vehicle_inspection` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '車検（0未選択/1あり/2なし）',
  `record_book` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '定期点検記録簿（0未選択/1あり/2なし）',
  `new_car_property` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '新車物件（0未選択/1該当/2非該当）',
  `non_smoking` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '禁煙車（0未選択/1該当/2非該当）',
  `officially_imported_car` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '正規輸入車（0未選択/1該当/2非該当）',
  `is_recycling_fee` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'リサイクル料（0未選択/1あり/2なし）',
  `registered_unused_car` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '登録済未使用車（0未選択/1該当/2非該当）',
  `test_car` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '展示・試乗車（0未選択/1該当/2非該当）',
  `rental_up` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'レンタカーアップ（0未選択/1該当/2非該当）',
  `body_type` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ボディタイプ（0未選択/1..11）',
  `body_color` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ボディ色（0未選択/1..15）',
  `color_code` varchar(32) DEFAULT NULL COMMENT 'カラーコード',
  `key_number` varchar(32) DEFAULT NULL COMMENT 'キー番号',
  `doors` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ドア数（0未選択/1..6）',
  `passengers` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '乗車定員（0未選択/1..10）',
  `handle` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ハンドル（0未選択/1右/2左）',
  `engine_type` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エンジン種別（0未選択/1ガソリン/2HV/3ディーゼル/4電気/5その他）',
  `supercharger_settings` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '過給機（0未選択/1ターボ/2スーパーチャージャー/3その他）',
  `drive_system` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '駆動方式（0未選択/1 2WD/2 4WD/3その他）',
  `welfare_vehicles` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '福祉車両（0未選択/1該当/2非該当）',
  `eco_car` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エコカー減税（0未選択/1該当/2非該当）',
  `chassis_number_suffix` varchar(16) DEFAULT NULL COMMENT '車台番号末尾',
  `legal_maintenance` text DEFAULT NULL COMMENT '法定整備（テキスト）',
  `guarantee` text DEFAULT NULL COMMENT '保証（テキスト）',
  `power_steering` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'パワステ',
  `abs` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ABS',
  `support_car` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'サポカー',
  `collision_damage` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '衝突被害軽減ブレーキ',
  `adaptive_cruise_control` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'アダプティブクルーズコントロール',
  `lane_keep_assist` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'レーンキープアシスト',
  `parking_assist` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'パーキングアシスト',
  `accidental_start_prevention_device` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '踏み間違い防止',
  `obstacle_sensor` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '障害物センサー',
  `airbag_driver_seat` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エアバッグ運転席',
  `airbag_passenger_seat` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エアバッグ助手席',
  `airbag_side` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エアバッグサイド',
  `airbag` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エアバッグ',
  `neck_shock_mitigation_headrest` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '頸部衝撃緩和ヘッドレスト',
  `all_around_camera` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '全周囲カメラ',
  `camera_back` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'バックカメラ',
  `monitor_blind_spot` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'BSMモニター',
  `monitor` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'モニター（名称未確定）',
  `anti_skid_device` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '横滑り防止',
  `hill_descent_control` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ヒルディセント',
  `idling_stop` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'アイドリングストップ',
  `anti_theft_device` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '盗難防止装置',
  `automatic_high_beam` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'オートマチックハイビーム',
  `air_conditioner_cooler` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エアコン・クーラー',
  `seat_air_conditioner` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'シートエアコン',
  `seat_heater` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'シートヒーター',
  `w_air_conditioner` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'Wエアコン',
  `hdd_car_navigation` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'カーナビ：HDD',
  `dvd_car_navigation` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'カーナビ：DVD',
  `tv` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'TV',
  `picture` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '映像',
  `music_server` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ミュージックサーバー',
  `is_music_player` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'プレイヤー接続可',
  `etc` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ETC',
  `power_supply` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '1500W給電',
  `drive_recorder` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ドライブレコーダー',
  `display_audio` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ディスプレイオーディオ',
  `rear_seat_monitor` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '後席モニター',
  `ottoman` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'オットマン',
  `keyless` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'キーレス（0未選択/1純正/2社外/3不明）',
  `smart_key` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'スマートキー（0未選択/1該当/2非該当）',
  `power_window` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'パワーウインドウ（0未選択/1該当/2非該当）',
  `sunroof_glassroof` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'サンルーフ/ガラスルーフ（0未選択/1純正/2社外/3不明）',
  `bench_seat` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ベンチシート（0未選択/1該当/2非該当）',
  `walk_through` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ウォークスルー（0未選択/1該当/2非該当）',
  `three_row_seats` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '3列シート（0未選択/1該当/2非該当）',
  `electric_seat` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '電動シート（0未選択/1該当/2非該当）',
  `full_flat_seat` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'フルフラットシート（0未選択/1該当/2非該当）',
  `genuine_leather_seat` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '本革シート（0未選択/1純正/2社外/3不明）',
  `slide_door` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'スライドドア（0未選択/1..6）',
  `electric_rear_gate` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '電動リアゲート（0未選択/1該当/2非該当）',
  `hid_led` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'HID/LED（0未選択/1ディスチャージ/2LED/3その他）',
  `front_fog_lamp` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'フロントフォグ（0未選択/1該当/2非該当）',
  `full_aero` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'フルエアロ（0未選択/1純正/2社外/3不明）',
  `low_down` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ローダウン（0未選択/1該当/2非該当）',
  `lift_up` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'リフトアップ（0未選択/1純正/2社外/3不明）',
  `air_suspension` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'エアサス（0未選択/1該当/2社外/3不明）',
  `aluminum_wheel` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'アルミホイール（0未選択/1純正/2社外/3不明）',
  `roof_rail` tinyint(3) UNSIGNED DEFAULT 0 COMMENT 'ルーフレール（0未選択/1該当/2非該当）',
  `cold_region_specification` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '寒冷地仕様（0未選択/1該当/2非該当）',
  `all_painted` tinyint(3) UNSIGNED DEFAULT 0 COMMENT '全塗装済（0未選択/1該当/2非該当）',
  `created_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT '作成日時',
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '更新日時',
  `deleted_at` datetime DEFAULT NULL COMMENT '論理削除日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='車両管理';
